use dblab;
create table student(Rollno varchar(10) not null,SName varchar(10) not null,City varchar(10) not null);
create table Course(CID varchar(10) not null,CName varchar(10) not null,Credit int(100) not null);
insert into student(Rollno,SName,City) values('CS20B1109','Nischal','Vijayawada');
insert into student(Rollno,SName,City) values('CS20B1110','Piyush','Delhi');
insert into student(Rollno,SName,City) values('CS20B1111','Tharak','Hyderabad');
insert into student(Rollno,SName,City) values('CS20B1112','Dileep','Bangalore');
insert into student(Rollno,SName,City) values('CS20B1113','Manavanth','Vijayawada');
insert into student(Rollno,SName,City) values('CS20B1114','Rudra','Hyderabad');
insert into student(Rollno,SName,City) values('CS20B1115','Vamsi','Hyderabad');
insert into student(Rollno,SName,City) values('CS20B1116','Atharva','Rajasthan');
insert into student(Rollno,SName,City) values('CS20B1117','Himanshu','Delhi');
insert into student(Rollno,SName,City) values('CS20B1119','Dheeraj','Himalayas');
insert into student(Rollno,SName,City) values('ME20B1072','Raj Gopal','Vizag');
select * from student;
insert into Course(CID,CName,Credit) values('CS1000','DSA',4);
insert into Course(CID,CName,Credit) values('CS1001','DAA',4);
insert into Course(CID,CName,Credit) values('CS1002','DSCS',2);
insert into Course(CID,CName,Credit) values('CS1003','OOPS',2);
insert into Course(CID,CName,Credit) values('CS1004','PSP',4);
insert into Course(CID,CName,Credit) values('CS1005','DSD',3);
insert into Course(CID,CName,Credit) values('CS1006','DBMS',4);
insert into Course(CID,CName,Credit) values('CS1007','COA',3);
insert into Course(CID,CName,Credit) values('CS1008','TOC',3);
insert into Course(CID,CName,Credit) values('CS1009','Materials',3);
select * from Course;
alter table student add marks int not null;
alter table student add department varchar(100) not null;
update student set marks=90,department='Computer Science';
update student set marks=70,department='Mechanical' where Rollno='ME20B1072';
alter table course modify column Credit varchar(10) not null;
alter table course add course_admission_date date not null;